favicon: /assets/img/identity/favicon.svg
primaryLogo: /assets/img/identity/primary-logo-light.svg

main_menu_settings:
  menu_items:
    - title: About the Count
      url: /about
      icon: person
    - title: Krigsvold & Matikonis
      url: /krigsvold-matikonis
      icon: landscape
    - title: FAQ
      url: /faq
      icon: quiz
    - title: Get Involved
      url: /get-involved
      icon: groups
    - title: The Fellowship
      url: /fellowship
      icon: school

footer_menu_settings:
  menu_items:
    - title: Privacy Policy
      url: /privacy-policy
    - title: Terms of Use
      url: /terms-of-use
    - title: Copyright
      url: /copyright

footer_settings:
  footer_tagline: A website of the House of Basu-Howard
